name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.5.0
      - run: npm install -g yarn
      - run: yarn install
        working-directory: ./app
      - run: yarn build
        working-directory: ./app
      - run: yarn test
        working-directory: ./app
